plugins {
	id 'java'
	id 'jacoco' 
}

repositories {
	mavenCentral()
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacocoTestReport { 
	dependsOn test
	reports {
		html.required = true
		xml.required = true
	}
}

jacocoTestCoverageVerification { 
	violationRules {
		rule {
			limit {
				counter = 'BRANCH'
				value = 'COVEREDRATIO'
				minimum = 0.90
			}
		}
	}
}

dependencies {
	testImplementation 'org.assertj:assertj-core:3.27.7'
	testImplementation 'org.junit.jupiter:junit-jupiter:6.1.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}